name: Génération de l'APK Android

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: ☕ Configuration de Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Installation des dépendances
        run: flutter pub get

      - name: 🏗️ Réparation de l'architecture du projet
        # Cette commande magique recrée les dossiers android/ et ios/ s'ils manquent
        run: flutter create .

      - name: 🛠️ Compilation de l'APK
        run: flutter build apk --release

      - name: 📤 Sauvegarde de l'APK généré
        uses: actions/upload-artifact@v4
        with:
          name: quete-du-graal-apk
          path: build/app/outputs/flutter-apk/app-release.apk
